config:
    shim:
        admin-lte:
            deps:
                - bootstrap
        bootstrap:
            deps:
                - jquery
        jquery.select2:
            deps:
                - jquery
            exports: Select2
        jquery.jqcron:
            deps:
                - jquery
        jquery.placeholder:
            deps:
                - jquery
        jquery.uploadify:
            deps:
                - jquery
        bootstrap.modal:
            deps:
                - jquery
                - bootstrap
        bootstrap.modalmanager:
            deps:
                - jquery
                - bootstrap
        bootstrap.material.datetimepicker:
            deps:
                - jquery
                - moment

        fos_router:
            exports: Routing
    paths:
        # External dependencies loaded through NPM/Yarn
        backbone: ../assets/backbone.js
        backbone.paginator: ../assets/backbone.paginator.js
        backbone.radio: ../assets/backbone.radio.js
        marionette: ../assets/backbone.marionette.js
        lodash: ../assets/lodash.js
        underscore: ../assets/underscore.js
        jquery: ../assets/jquery.js
        bootstrap: ../assets/bootstrap.js
        accounting: ../assets/accounting.js
        parsley: ../assets/parsley.js
        moment: ../assets/moment.js
        jquery.select2: ../assets/select2.js
        handlebars.runtime: ../assets/handlebars.runtime.js
        jquery.placeholder: ../assets/jquery.placeholder.js
        bootstrap.material.datetimepicker: ../assets/material-datetimepicker.js
        admin-lte: ../assets/adminlte.min.js

        # External Dependencies that don't have an NPM package
        jquery.jqcron: solidinvoicecore/js/lib/jquery/jqcron.js
        jquery.uploadify: solidinvoicecore/js/lib/jquery/uploadify.min.js
        bootstrap.modal: solidinvoicecore/js/lib/bootstrap/modal.js
        bootstrap.modalmanager: solidinvoicecore/js/lib/bootstrap/modalmanager.js

        routing: solidinvoicecore/js/extend/routing
        fos_router: fosjsrouting/js/router.js
        Translator: bazingajstranslation/js/translator.min.js
        core: solidinvoicecore/js/
        core/view: solidinvoicecore/js/itemview.js
        util/form/collection: solidinvoicecore/js/util/form/collection.js
        template: ../js/hbs-templates.js
        fos_routing_data: ../js/fos_js_routes.js
    map:
        '*':
            translator: solidinvoicecore/js/extend/translator
            handlebars.runtime: solidinvoicecore/js/extend/handlebars/helpers
            parsley: solidinvoicecore/js/extend/parsley
            bootstrap.modal: solidinvoicecore/js/extend/modal
        solidinvoicecore/js/extend/handlebars/helpers:
            handlebars.runtime: handlebars.runtime
            routing: routing
        solidinvoicecore/js/extend/translator:
            translation_data: translation_data
        solidinvoicecore/js/extend/parsley:
            parsley: parsley
        solidinvoicecore/js/extend/modal:
            bootstrap.modal: bootstrap.modal
build:
    paths:
        core: 'empty:'
        client: 'empty:'
        quote: 'empty:'
        invoice: 'empty:'
        profile: 'empty:'
        user: 'empty:'
        payments: 'empty:'
        moment: 'empty:'
        grid: 'empty:'
        tax: 'empty:'
        translation_data: 'empty:'
        bootstrap.material.datetimepicker: 'empty:'
