imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: payum.yml }
    - { resource: workflow.yml }
    - { resource: assetVersion.php }

framework:
    esi: null
    translator:
        fallback: en
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enabled: true
        enable_annotations: true
        strict_email: true
    default_locale: '%locale%'
    session:
        name: SOLIDINVOICE_APP
    fragments: null
    http_method_override: true
    serializer: { enable_annotations: true }

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SolidInvoiceCoreBundle:Form:fields.html.twig'

doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.5
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            money: SolidInvoice\MoneyBundle\Doctrine\Types\MoneyType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                hydrators:
                    money: SolidInvoice\MoneyBundle\Doctrine\Hydrator\MoneyHydrator
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                    archivable:
                        class: SolidInvoice\CoreBundle\Doctrine\Filter\ArchivableFilter
                        enabled: true
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity'
                        alias: GedmoTranslatable
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity'
                        alias: GedmoTranslator
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                        alias: GedmoLoggable
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'
                        alias: GedmoTree
                        is_bundle: false
                    payum:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping'
                        prefix: Payum\Core\Model

swiftmailer:
    transport: '%env(mailer_transport)%'
    host: '%env(mailer_host)%'
    username: '%env(mailer_user)%'
    password: '%env(mailer_password)%'
    encryption: '%env(mailer_encryption)%'
    port: '%env(mailer_port)%'
    spool:
        type: memory

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm: null

fos_user:
    from_email:
        address: 'info@solidinvoice.co'
        sender_name: 'SolidInvoice'
    db_driver: orm
    firewall_name: main
    user_class: SolidInvoice\UserBundle\Entity\User
    profile:
        form:
            type: SolidInvoice\UserBundle\Form\Type\ProfileType
    registration:
        form:
            type: SolidInvoice\UserBundle\Form\Type\UserType

oro_require_js:
    config:
        waitSeconds: 0
        enforceDefine: false
        scriptType: text/javascript
    js_engine: node
    base_url: assets

api_platform:
    title: 'API'
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']
